name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - name: Check out repo code
        uses: actions/checkout@4
      - run: |
         # build image
         docker build -t alex-test-blazor-thing
         docker run -d alex-test-blazor-thing
         echo "made it to the end 🔥🔥"
