name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - name: Check out repo code
        uses: actions checkout@v4
      - run: |
         # build image
         docker build -t kalin-test-blazor-thing .
         #run image
         docker run -d \
           -p 39482:8080 \
           --name kalin-test-blazor-thing \
           kalin-test-blazor-thing

         echo "made it to the end 🔥"
